/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2014, STMicroelectronics International N.V.
 */

#ifndef TEE_SYSCALL_NUMBERS_H
#define TEE_SYSCALL_NUMBERS_H

#define TEE_SCN_RETURN				0
#define TEE_SCN_LOG				1
#define TEE_SCN_PANIC				2
#define TEE_SCN_GET_PROPERTY			3
#define TEE_SCN_GET_PROPERTY_NAME_TO_INDEX	4
#define TEE_SCN_OPEN_TA_SESSION			5
#define TEE_SCN_CLOSE_TA_SESSION		6
#define TEE_SCN_INVOKE_TA_COMMAND		7
#define TEE_SCN_CHECK_ACCESS_RIGHTS		8
#define TEE_SCN_GET_CANCELLATION_FLAG		9
#define TEE_SCN_UNMASK_CANCELLATION		10
#define TEE_SCN_MASK_CANCELLATION		11
#define TEE_SCN_WAIT				12
#define TEE_SCN_GET_TIME			13
#define TEE_SCN_SET_TA_TIME			14
#define TEE_SCN_CRYP_STATE_ALLOC		15
#define TEE_SCN_CRYP_STATE_COPY			16
#define TEE_SCN_CRYP_STATE_FREE			17
#define TEE_SCN_HASH_INIT			18
#define TEE_SCN_HASH_UPDATE			19
#define TEE_SCN_HASH_FINAL			20
#define TEE_SCN_CIPHER_INIT			21
#define TEE_SCN_CIPHER_UPDATE			22
#define TEE_SCN_CIPHER_FINAL			23
#define TEE_SCN_CRYP_OBJ_GET_INFO		24
#define TEE_SCN_CRYP_OBJ_RESTRICT_USAGE		25
#define TEE_SCN_CRYP_OBJ_GET_ATTR		26
#define TEE_SCN_CRYP_OBJ_ALLOC			27
#define TEE_SCN_CRYP_OBJ_CLOSE			28
#define TEE_SCN_CRYP_OBJ_RESET			29
#define TEE_SCN_CRYP_OBJ_POPULATE		30
#define TEE_SCN_CRYP_OBJ_COPY			31
#define TEE_SCN_CRYP_DERIVE_KEY			32
#define TEE_SCN_CRYP_RANDOM_NUMBER_GENERATE	33
#define TEE_SCN_AUTHENC_INIT			34
#define TEE_SCN_AUTHENC_UPDATE_AAD		35
#define TEE_SCN_AUTHENC_UPDATE_PAYLOAD		36
#define TEE_SCN_AUTHENC_ENC_FINAL		37
#define TEE_SCN_AUTHENC_DEC_FINAL		38
#define TEE_SCN_ASYMM_OPERATE			39
#define TEE_SCN_ASYMM_VERIFY			40
#define TEE_SCN_STORAGE_OBJ_OPEN		41
#define TEE_SCN_STORAGE_OBJ_CREATE		42
#define TEE_SCN_STORAGE_OBJ_DEL			43
#define TEE_SCN_STORAGE_OBJ_RENAME		44
#define TEE_SCN_STORAGE_ENUM_ALLOC		45
#define TEE_SCN_STORAGE_ENUM_FREE		46
#define TEE_SCN_STORAGE_ENUM_RESET		47
#define TEE_SCN_STORAGE_ENUM_START		48
#define TEE_SCN_STORAGE_ENUM_NEXT		49
#define TEE_SCN_STORAGE_OBJ_READ		50
#define TEE_SCN_STORAGE_OBJ_WRITE		51
#define TEE_SCN_STORAGE_OBJ_TRUNC		52
#define TEE_SCN_STORAGE_OBJ_SEEK		53
#define TEE_SCN_CRYP_OBJ_GENERATE_KEY		54
/* Deprecated Secure Element API syscalls return TEE_ERROR_NOT_SUPPORTED */
#define TEE_SCN_SE_SERVICE_OPEN__DEPRECATED		55
#define TEE_SCN_SE_SERVICE_CLOSE__DEPRECATED		56
#define TEE_SCN_SE_SERVICE_GET_READERS__DEPRECATED	57
#define TEE_SCN_SE_READER_GET_PROP__DEPRECATED		58
#define TEE_SCN_SE_READER_GET_NAME__DEPRECATED		59
#define TEE_SCN_SE_READER_OPEN_SESSION__DEPRECATED	60
#define TEE_SCN_SE_READER_CLOSE_SESSIONS__DEPRECATED	61
#define TEE_SCN_SE_SESSION_IS_CLOSED__DEPRECATED	62
#define TEE_SCN_SE_SESSION_GET_ATR__DEPRECATED		63
#define TEE_SCN_SE_SESSION_OPEN_CHANNEL__DEPRECATED	64
#define TEE_SCN_SE_SESSION_CLOSE__DEPRECATED		65
#define TEE_SCN_SE_CHANNEL_SELECT_NEXT__DEPRECATED	66
#define TEE_SCN_SE_CHANNEL_GET_SELECT_RESP__DEPRECATED	67
#define TEE_SCN_SE_CHANNEL_TRANSMIT__DEPRECATED		68
#define TEE_SCN_SE_CHANNEL_CLOSE__DEPRECATED		69
/* End of deprecated Secure Element API syscalls */
#define TEE_SCN_CACHE_OPERATION			70
#define TEE_SCN_RESERVED_71			71
#define TEE_SCN_RESERVED_72			72
#define TEE_SCN_RESERVED_73			73
#define TEE_SCN_RESERVED_74			74
#define TEE_SCN_RESERVED_75			75
#define TEE_SCN_RESERVED_76			76
#define TEE_SCN_RESERVED_77			77
#define TEE_SCN_RESERVED_78			78
#define TEE_SCN_RESERVED_79			79
#define TEE_SCN_RESERVED_80			80
#define TEE_SCN_RESERVED_81			81
#define TEE_SCN_RESERVED_82			82
#define TEE_SCN_RESERVED_83			83
#define TEE_SCN_RESERVED_84			84
#define TEE_SCN_RESERVED_85			85
#define TEE_SCN_RESERVED_86			86
#define TEE_SCN_RESERVED_87			87
#define TEE_SCN_RESERVED_88			88
#define TEE_SCN_RESERVED_89			89
#define TEE_SCN_RESERVED_90			90
#define TEE_SCN_RESERVED_91			91
#define TEE_SCN_RESERVED_92			92
#define TEE_SCN_RESERVED_93			93
#define TEE_SCN_RESERVED_94			94
#define TEE_SCN_RESERVED_95			95
#define TEE_SCN_RESERVED_96			96
#define TEE_SCN_RESERVED_97			97
#define TEE_SCN_RESERVED_98			98
#define TEE_SCN_RESERVED_99			99
#define TEE_SCN_RESERVED_100			100
#define TEE_SCN_RESERVED_101			101
#define TEE_SCN_RESERVED_102			102
#define TEE_SCN_RESERVED_103			103
#define TEE_SCN_RESERVED_104			104
#define TEE_SCN_RESERVED_105			105
#define TEE_SCN_RESERVED_106			106
#define TEE_SCN_RESERVED_107			107
#define TEE_SCN_RESERVED_108			108
#define TEE_SCN_RESERVED_109			109
#define TEE_SCN_RESERVED_110			110
#define TEE_SCN_RESERVED_111			111
#define TEE_SCN_RESERVED_112			112
#define TEE_SCN_RESERVED_113			113
#define TEE_SCN_RESERVED_114			114
#define TEE_SCN_RESERVED_115			115
#define TEE_SCN_RESERVED_116			116
#define TEE_SCN_RESERVED_117			117
#define TEE_SCN_RESERVED_118			118
#define TEE_SCN_RESERVED_119			119
#define TEE_SCN_RESERVED_120			120
#define TEE_SCN_RESERVED_121			121
#define TEE_SCN_RESERVED_122			122
#define TEE_SCN_RESERVED_123			123
#define TEE_SCN_RESERVED_124			124
#define TEE_SCN_RESERVED_125			125
#define TEE_SCN_RESERVED_126			126
#define TEE_SCN_RESERVED_127			127
#define TEE_SCN_EXTEND_FUNC			128
#define TEE_SCN_MAX				128

/* Maximum number of allowed arguments for a syscall */
#define TEE_SVC_MAX_ARGS			8

#endif /* TEE_SYSCALL_NUMBERS_H */
